apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: kasuni77/ctse_assignment:257c8452a130724cfa838ccdd25bcc5cd2df797e
        ports:
        - containerPort: 3000